#ifndef __WMMAE_MMA_F32_F32_DETAIL_INCLUDE_SIMT_HPP__
#define __WMMAE_MMA_F32_F32_DETAIL_INCLUDE_SIMT_HPP__
#ifndef WMMAE_NOT_INCLUDE_WMMAE_SIMT_HEADER
#include <wmma_extension/mma_simt.hpp>
#endif
#endif
